#!/bin/bash
pwd
echo "#####################"
ls -al
echo "#####################"
cd /app
./proxy.exe http -t tcp -p “0.0.0.0:8090” -T 

wss -P “your.domain.com:8443” –local-ws-method=“chacha20-ietf-poly1305” –

local-ws-password=“snail007/goproxy”
